### ISSUE TITLE
This plugin is resulting crashing application on few iPhone devices

### ISSUE THREAD

**Issue by abdullah432** [koiralapankaj7/drishya_picker#20] opened 2021-11-10 08:35 UTC
**Describe the bug**
In one of our application we use this plugin and on our devices app was working fine but some user was complaining about the app crash, after investigation, we found that when on particular iPhone devices user navigate to the page where this plugin was used, crash the application. So we have to remove this plugin from one of our applications. I'm still using this plugin on another application.

**Log**
Didn't look helpful but this was the log we're getting
```
An Observatory debugger and profiler on iPhone is available at:
http://127.0.0.1:52299/BanmUcoploY=/
The Flutter DevTools debugger and profiler on iPhone is available at:
http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A52299%2FBanmUcoploY%3D%2F
[....] Disconnected 00008101-0016606E1A86001E
8.6.0 - [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '923387996009'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
[core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
AVDRegister - AppleAVD HEVC codec registered
AVDRegister - AppleAVD H264 codec registered
AVDRegister - AppleAVD Leghorn codec registered
flutter: query:
* thread #4, queue = 'com.apple.root.user-initiated-qos', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
frame #0: 0x00000001c3e53f78 vImagevConvert_420Yp8_CbCr8ToARGB8888_vec + 704 vImagevConvert_420Yp8_CbCr8ToARGB8888_vec:
-> 0x1c3e53f78 <+704>: stp q21, q19, [x22]
0x1c3e53f7c <+708>: tbl.16b v19, { v20 }, v16
0x1c3e53f80 <+712>: zip1.16b v20, v17, v26
0x1c3e53f84 <+716>: zip2.16b v21, v17, v26
Target 0: (Runner) stopped.

```
**Expected behavior**

**Screenshots: Device Info**
![8E4F2F35-0E25-4756-9B7D-897C4AFC625C](https://user-images.githubusercontent.com/48089976/141077896-b22f4ab0-8102-4d83-818c-17d5c7eee147.jpeg)

**Additional context**
We didn't add microphone permission to Info.plist because we didn't need that permission from the user, not sure if this was causing the issue.

```
<key>NSMicrophoneUsageDescription</key>
<string>Replace with your permission description..</string>
```

**Comment by koiralapankaj7** [comment] 2021-12-30 16:45
Unable to reproduce. Please check the new version if that solves your issue. Closing for now, if you encounter this again feel free to open this ticket again.

**Closed by koiralapankaj7** 2021-12-30 16:45 UTC
