### ISSUE TITLE
use photo editor separately

### ISSUE THREAD

**Issue by husen-hn** [koiralapankaj7/drishya_picker#17] opened 2021-09-01 05:46 UTC
**Is your feature request related to a problem? Please describe.**
is there a way to use the photo edits option separately from the photo picker part?

**Additional context**

**Comment by koiralapankaj7** [comment] 2021-09-02 05:41
duplicate of https://github.com/koiralapankaj7/drishya_picker/issues/16#issue-984639542

**Closed by koiralapankaj7** 2021-09-02 05:41 UTC
Labels: duplicate, feature
